const data = [
    {
      ID: 'MS003',
      Revenue: 49174,
      Cost: 23120,
      'Currency Unit': 'SGD',
      'Total customer': '331',
      'Date from': '3/15/21',
      'Time From': '14:00',
      'Date to': '3/21/21',
      'Time To': '16:00',
      'From ': 'Sydney, Australia',
      To: 'Andelaide, Australia',
      Column1: '26,586',
      Captain: 'Leesin',
      Aircraft: 'Boeing 401',
      'Flight time': 146
    },
    {
      ID: 'MS005',
      Revenue: 36697,
      Cost: 30877,
      'Currency Unit': 'USD',
      'Total customer': '260',
      'Date from': '3/17/21',
      'Time From': '23:00',
      'Date to': '3/19/21',
      'Time To': '6:00',
      'From ': 'Danang, Vietnam',
      To: 'Andelaide, Australia',
      Column1: '7,973',
      Captain: 'Kassadin',
      Aircraft: 'Boeing501',
      'Flight time': 31
    },
    {
      ID: 'MH004',
      Revenue: 36831,
      Cost: 15705,
      'Currency Unit': 'USD',
      'Total customer': '359',
      'Date from': '3/16/21',
      'Time From': '21:00',
      'Date to': '3/17/21',
      'Time To': '16:00',
      'From ': 'Seoul, Korea',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '28,939',
      Captain: 'Katarina',
      Aircraft: 'Boeing 403',
      'Flight time': 19
    },
    {
      ID: 'MS001',
      Revenue: 36953,
      Cost: 30684,
      'Currency Unit': 'USD',
      'Total customer': '340',
      'Date from': '3/13/21',
      'Time From': '12:00',
      'Date to': '3/18/21',
      'Time To': '13:00',
      'From ': 'Melbounrne, Australia',
      To: 'Bankok, Thailand',
      Column1: '8,588',
      Captain: 'John Cena',
      Aircraft: 'Boeing 777',
      'Flight time': 121
    },
    {
      ID: 'MH006',
      Revenue: 37957,
      Cost: 30509,
      'Currency Unit': 'USD',
      'Total customer': '413',
      'Date from': '3/17/21',
      'Time From': '7:00',
      'Date to': '3/22/21',
      'Time To': '7:00',
      'From ': 'Sydney, Australia',
      To: 'Bankok, Thailand',
      Column1: '10,203',
      Captain: 'Donkey Hote',
      Aircraft: 'Boeing502',
      'Flight time': 120
    },
    {
      ID: 'MH004',
      Revenue: 52053,
      Cost: 29702,
      'Currency Unit': 'AUD',
      'Total customer': '370',
      'Date from': '3/13/21',
      'Time From': '20:00',
      'Date to': '3/15/21',
      'Time To': '16:00',
      'From ': 'Sydney, Australia',
      To: 'Bankok, Thailand',
      Column1: '22,351',
      Captain: 'Katarina',
      Aircraft: 'Boeing 403',
      'Flight time': 44
    },
    {
      ID: 'MS005',
      Revenue: 38104,
      Cost: 32113,
      'Currency Unit': 'USD',
      'Total customer': '356',
      'Date from': '3/13/21',
      'Time From': '17:00',
      'Date to': '3/18/21',
      'Time To': '6:00',
      'From ': 'Danang, Vietnam',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '8,206',
      Captain: 'Kassadin',
      Aircraft: 'Boeing501',
      'Flight time': 109
    },
    {
      ID: 'MS001',
      Revenue: 38485,
      Cost: 28128,
      'Currency Unit': 'USD',
      'Total customer': '206',
      'Date from': '3/19/21',
      'Time From': '5:00',
      'Date to': '3/22/21',
      'Time To': '23:00',
      'From ': 'Seoul, Korea',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '14,187',
      Captain: 'John Cena',
      Aircraft: 'Boeing 777',
      'Flight time': 90
    },
    {
      ID: 'MS003',
      Revenue: 52725,
      Cost: 39625,
      'Currency Unit': 'SGD',
      'Total customer': '260',
      'Date from': '3/16/21',
      'Time From': '15:00',
      'Date to': '3/17/21',
      'Time To': '22:00',
      'From ': 'Sydney, Australia',
      To: 'Bankok, Thailand',
      Column1: '13,367',
      Captain: 'Leesin',
      Aircraft: 'Boeing 401',
      'Flight time': 31
    },
    {
      ID: 'MS005',
      Revenue: 54253,
      Cost: 21322,
      'Currency Unit': 'AUD',
      'Total customer': '451',
      'Date from': '3/19/21',
      'Time From': '5:00',
      'Date to': '3/23/21',
      'Time To': '9:00',
      'From ': 'Seoul, Korea',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '32,931',
      Captain: 'Kassadin',
      Aircraft: 'Boeing501',
      'Flight time': 100
    },
    {
      ID: 'MS003',
      Revenue: 39860,
      Cost: 21502,
      'Currency Unit': 'USD',
      'Total customer': '303',
      'Date from': '3/19/21',
      'Time From': '2:00',
      'Date to': '3/23/21',
      'Time To': '3:00',
      'From ': 'Melbounrne, Australia',
      To: 'Kyoto, Japan',
      Column1: '25,148',
      Captain: 'Leesin',
      Aircraft: 'Boeing 401',
      'Flight time': 97
    },
    {
      ID: 'MH002',
      Revenue: 54714,
      Cost: 42547,
      'Currency Unit': 'AUD',
      'Total customer': '487',
      'Date from': '3/15/21',
      'Time From': '3:00',
      'Date to': '3/16/21',
      'Time To': '7:00',
      'From ': 'Melbounrne, Australia',
      To: 'Kyoto, Japan',
      Column1: '12,167',
      Captain: 'Garen',
      Aircraft: 'Boeing 788',
      'Flight time': 28
    },
    {
      ID: 'MH002',
      Revenue: 40507,
      Cost: 24527,
      'Currency Unit': 'USD',
      'Total customer': '493',
      'Date from': '3/14/21',
      'Time From': '5:00',
      'Date to': '3/19/21',
      'Time To': '12:00',
      'From ': 'Danang, Vietnam',
      To: 'Kyoto, Japan',
      Column1: '21,891',
      Captain: 'Garen',
      Aircraft: 'Boeing 788',
      'Flight time': 127
    },
    {
      ID: 'MH004',
      Revenue: 41595,
      Cost: 31376,
      'Currency Unit': 'USD',
      'Total customer': '467',
      'Date from': '3/17/21',
      'Time From': '7:00',
      'Date to': '3/23/21',
      'Time To': '8:00',
      'From ': 'Melbounrne, Australia',
      To: 'Bankok, Thailand',
      Column1: '13,998',
      Captain: 'Katarina',
      Aircraft: 'Boeing 403',
      'Flight time': 145
    },
    {
      ID: 'MA007',
      Revenue: 57089,
      Cost: 33386,
      'Currency Unit': 'AUD',
      'Total customer': '389',
      'Date from': '3/12/21',
      'Time From': '2:00',
      'Date to': '3/14/21',
      'Time To': '4:00',
      'From ': 'Danang, Vietnam',
      To: 'Andelaide, Australia',
      Column1: '23,703',
      Captain: 'Jackie Chan',
      Aircraft: 'Boeing503',
      'Flight time': 50
    },
    {
      ID: 'MS005',
      Revenue: 57672,
      Cost: 23527,
      'Currency Unit': 'SGD',
      'Total customer': '335',
      'Date from': '3/14/21',
      'Time From': '5:00',
      'Date to': '3/18/21',
      'Time To': '2:00',
      'From ': 'Melbounrne, Australia',
      To: 'Andelaide, Australia',
      Column1: '34,842',
      Captain: 'Kassadin',
      Aircraft: 'Boeing501',
      'Flight time': 93
    },
    {
      ID: 'MA007',
      Revenue: 39351,
      Cost: 16535,
      'Currency Unit': 'EURO',
      'Total customer': '253',
      'Date from': '3/18/21',
      'Time From': '15:00',
      'Date to': '3/21/21',
      'Time To': '23:00',
      'From ': 'Melbounrne, Australia',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '34,570',
      Captain: 'Jackie Chan',
      Aircraft: 'Boeing503',
      'Flight time': 80
    },
    {
      ID: 'MH006',
      Revenue: 39680,
      Cost: 13477,
      'Currency Unit': 'EURO',
      'Total customer': '374',
      'Date from': '3/20/21',
      'Time From': '9:00',
      'Date to': '3/21/21',
      'Time To': '3:00',
      'From ': 'Melbounrne, Australia',
      To: 'Ho Chi Minh, Vietnam',
      Remark: 'Nothing to say',
      Column1: '39,702',
      Captain: 'Donkey Hote',
      Aircraft: 'Boeing502',
      'Flight time': 18
    },
    {
      ID: 'MS001',
      Revenue: 59203,
      Cost: 35044,
      'Currency Unit': 'SGD',
      'Total customer': '312',
      'Date from': '3/15/21',
      'Time From': '10:00',
      'Date to': '3/18/21',
      'Time To': '15:00',
      'From ': 'Seoul, Korea',
      To: 'Ho Chi Minh, Vietnam',
      Remark: '?',
      Column1: '24,652',
      Captain: 'John Cena',
      Aircraft: 'Boeing 777',
      'Flight time': 77
    },
    {
      ID: 'MA007',
      Revenue: 40291,
      Cost: 18511,
      'Currency Unit': 'EURO',
      'Total customer': '452',
      'Date from': '3/17/21',
      'Time From': '8:00',
      'Date to': '3/20/21',
      'Time To': '5:00',
      'From ': 'Melbounrne, Australia',
      To: 'Bankok, Thailand',
      Column1: '33,000',
      Captain: 'Jackie Chan',
      Aircraft: 'Boeing503',
      'Flight time': 69
    },
    {
      ID: 'MH002',
      Revenue: 60302,
      Cost: 38342,
      'Currency Unit': 'SGD',
      'Total customer': '394',
      'Date from': '3/16/21',
      'Time From': '15:00',
      'Date to': '3/18/21',
      'Time To': '13:00',
      'From ': 'Sydney, Australia',
      To: 'Kyoto, Japan',
      Column1: '22,409',
      Captain: 'Garen',
      Aircraft: 'Boeing 788',
      'Flight time': 46
    },
    {
      ID: 'MA007',
      Revenue: 61701,
      Cost: 20026,
      'Currency Unit': 'AUD',
      'Total customer': '493',
      'Date from': '3/15/21',
      'Time From': '14:00',
      'Date to': '3/16/21',
      'Time To': '6:00',
      'From ': 'Seoul, Korea',
      To: 'Bankok, Thailand',
      Column1: '41,675',
      Captain: 'Jackie Chan',
      Aircraft: 'Boeing503',
      'Flight time': 16
    },
    {
      ID: 'MH006',
      Revenue: 45678,
      Cost: 16161,
      'Currency Unit': 'USD',
      'Total customer': '310',
      'Date from': '3/14/21',
      'Time From': '4:00',
      'Date to': '3/18/21',
      'Time To': '4:00',
      'From ': 'Sydney, Australia',
      To: 'Andelaide, Australia',
      Column1: '40,434',
      Captain: 'Donkey Hote',
      Aircraft: 'Boeing502',
      'Flight time': 96
    },
    {
      ID: 'MA007',
      Revenue: 61520,
      Cost: 42407,
      'Currency Unit': 'SGD',
      'Total customer': '487',
      'Date from': '3/20/21',
      'Time From': '20:00',
      'Date to': '3/21/21',
      'Time To': '3:00',
      'From ': 'Seoul, Korea',
      To: 'Andelaide, Australia',
      Remark: 'Enough flight',
      Column1: '19,504',
      Captain: 'Jackie Chan',
      Aircraft: 'Boeing503',
      'Flight time': 7
    },
    {
      ID: 'MA007',
      Revenue: 46334,
      Cost: 31548,
      'Currency Unit': 'USD',
      'Total customer': '318',
      'Date from': '3/14/21',
      'Time From': '22:00',
      'Date to': '3/21/21',
      'Time To': '14:00',
      'From ': 'Melbounrne, Australia',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '20,255',
      Captain: 'Jackie Chan',
      Aircraft: 'Boeing503',
      'Flight time': 160
    },
    {
      ID: 'MS003',
      Revenue: 42189,
      Cost: 26354,
      'Currency Unit': 'EURO',
      'Total customer': '472',
      'Date from': '3/17/21',
      'Time From': '11:00',
      'Date to': '3/20/21',
      'Time To': '12:00',
      'From ': 'Melbounrne, Australia',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '23,993',
      Captain: 'Leesin',
      Aircraft: 'Boeing 401',
      'Flight time': 73
    },
    {
      ID: 'MS001',
      Revenue: 62728,
      Cost: 20451,
      'Currency Unit': 'SGD',
      'Total customer': '497',
      'Date from': '3/14/21',
      'Time From': '4:00',
      'Date to': '3/16/21',
      'Time To': '10:00',
      'From ': 'Melbounrne, Australia',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '43,140',
      Captain: 'John Cena',
      Aircraft: 'Boeing 777',
      'Flight time': 54
    },
    {
      ID: 'MA007',
      Revenue: 47334,
      Cost: 21101,
      'Currency Unit': 'USD',
      'Total customer': '354',
      'Date from': '3/13/21',
      'Time From': '5:00',
      'Date to': '3/18/21',
      'Time To': '8:00',
      'From ': 'Sydney, Australia',
      To: 'Bankok, Thailand',
      Column1: '35,935',
      Captain: 'Jackie Chan',
      Aircraft: 'Boeing503',
      'Flight time': 123
    },
    {
      ID: 'MH006',
      Revenue: 63731,
      Cost: 40574,
      'Currency Unit': 'SGD',
      'Total customer': '304',
      'Date from': '3/15/21',
      'Time From': '7:00',
      'Date to': '3/19/21',
      'Time To': '1:00',
      'From ': 'Danang, Vietnam',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '23,630',
      Captain: 'Donkey Hote',
      Aircraft: 'Boeing502',
      'Flight time': 90
    },
    {
      ID: 'MH002',
      Revenue: 63755,
      Cost: 31491,
      'Currency Unit': 'SGD',
      'Total customer': '359',
      'Date from': '3/19/21',
      'Time From': '14:00',
      'Date to': '3/23/21',
      'Time To': '19:00',
      'From ': 'Melbounrne, Australia',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '32,922',
      Captain: 'Garen',
      Aircraft: 'Boeing 788',
      'Flight time': 101
    },
    {
      ID: 'MH004',
      Revenue: 43247,
      Cost: 27971,
      'Currency Unit': 'EURO',
      'Total customer': '271',
      'Date from': '3/19/21',
      'Time From': '5:00',
      'Date to': '3/21/21',
      'Time To': '19:00',
      'From ': 'Melbounrne, Australia',
      To: 'Kyoto, Japan',
      Column1: '23,145',
      Captain: 'Katarina',
      Aircraft: 'Boeing 403',
      'Flight time': 62
    },
    {
      ID: 'MS001',
      Revenue: 43318,
      Cost: 25357,
      'Currency Unit': 'EURO',
      'Total customer': '325',
      'Date from': '3/12/21',
      'Time From': '21:00',
      'Date to': '3/15/21',
      'Time To': '20:00',
      'From ': 'Melbounrne, Australia',
      To: 'Andelaide, Australia',
      Remark: '-',
      Column1: '27,215',
      Captain: 'John Cena',
      Aircraft: 'Boeing 777',
      'Flight time': 71
    },
    {
      ID: 'MH004',
      Revenue: 66711,
      Cost: 38805,
      'Currency Unit': 'AUD',
      'Total customer': '380',
      'Date from': '3/14/21',
      'Time From': '12:00',
      'Date to': '3/17/21',
      'Time To': '8:00',
      'From ': 'Sydney, Australia',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '27,906',
      Captain: 'Katarina',
      Aircraft: 'Boeing 403',
      'Flight time': 68
    },
    {
      ID: 'MH004',
      Revenue: 66133,
      Cost: 38294,
      'Currency Unit': 'SGD',
      'Total customer': '467',
      'Date from': '3/18/21',
      'Time From': '16:00',
      'Date to': '3/23/21',
      'Time To': '12:00',
      'From ': 'Melbounrne, Australia',
      To: 'Kyoto, Japan',
      Column1: '28,407',
      Captain: 'Katarina',
      Aircraft: 'Boeing 403',
      'Flight time': 116
    },
    {
      ID: 'MH006',
      Revenue: 67694,
      Cost: 22878,
      'Currency Unit': 'AUD',
      'Total customer': '299',
      'Date from': '3/19/21',
      'Time From': '16:00',
      'Date to': '3/23/21',
      'Time To': '12:00',
      'From ': 'Seoul, Korea',
      To: 'Andelaide, Australia',
      Column1: '44,816',
      Captain: 'Donkey Hote',
      Aircraft: 'Boeing502',
      'Flight time': 92
    },
    {
      ID: 'MA007',
      Revenue: 67451,
      Cost: 41034,
      'Currency Unit': 'SGD',
      'Total customer': '481',
      'Date from': '3/16/21',
      'Time From': '4:00',
      'Date to': '3/22/21',
      'Time To': '21:00',
      'From ': 'Seoul, Korea',
      To: 'Ho Chi Minh, Vietnam',
      Column1: '26,957',
      Captain: 'Jackie Chan',
      Aircraft: 'Boeing503',
      'Flight time': 161
    },
    {
      ID: 'MS005',
      Revenue: 45603,
      Cost: 28057,
      'Currency Unit': 'EURO',
      'Total customer': '454',
      'Date from': '3/16/21',
      'Time From': '14:00',
      'Date to': '3/17/21',
      'Time To': '23:00',
      'From ': 'Sydney, Australia',
      To: 'Andelaide, Australia',
      Column1: '26,585',
      Captain: 'Kassadin',
      Aircraft: 'Boeing501',
      'Flight time': 33
    },
    {
      ID: 'MS003',
      Revenue: 46184,
      Cost: 23777,
      'Currency Unit': 'EURO',
      'Total customer': '270',
      'Date from': '3/13/21',
      'Time From': '15:00',
      'Date to': '3/17/21',
      'Time To': '21:00',
      'From ': 'Melbounrne, Australia',
      To: 'Andelaide, Australia',
      Column1: '33,950',
      Captain: 'Leesin',
      Aircraft: 'Boeing 401',
      'Flight time': 102
    }
]

function getObjectList(data, type) {
    const collection = {}
    data.forEach(item => {
        if ([...Object.keys(collection)].includes(item[type]))
        collection[item[type]] += 1;
    else
        collection[item[type]] = 1;
    })
    
    return collection
}

function getMaxValue(collection) {
    const max = Math.max(...Object.values(collection)) 
    for (let i = 0; i < Object.keys(collection).length; i++) {
        if (collection[Object.keys(collection)[i]] === max) 
           return Object.keys(collection)[i]
    }
}

function getWeeklyReportData(dataSheet) {
    const weeklyReport = {}

    const airCrafts = getObjectList(dataSheet, 'Aircraft')
    const departure = getObjectList(dataSheet, 'From ')
    const destination = getObjectList(dataSheet, 'To')
    
    const departureCountry = {}
    Object.keys(departure).forEach(item => {
        if (Object.keys(departureCountry).includes(item.trim().split(',')[1]))
            departureCountry[item.trim().split(',')[1]] += departure[item]
        else
            departureCountry[item.trim().split(',')[1]] = departure[item]
    })

    let revenuePerDay = [];
    dataSheet.forEach(item => {
        revenuePerDay.push(item['Revenue'] - item['Cost'])
    })

    weeklyReport['Most used air craft'] = getMaxValue(airCrafts)
    weeklyReport['Most departure location'] = getMaxValue(departure)
    weeklyReport['Most destination'] = getMaxValue(destination)
    
    weeklyReport['Total customers'] = dataSheet.reduce((prev, curr) => prev += parseInt(curr['Total customer']), 0)
    weeklyReport['Total flight time'] = dataSheet.reduce((prev, curr) => prev += parseInt(curr['Flight time']), 0)
    weeklyReport['Average flight time'] = weeklyReport['Total flight time']/dataSheet.length
    weeklyReport['Revenue per day'] = revenuePerDay
    weeklyReport['Departure country'] = departureCountry
    return weeklyReport
}

module.exports = getWeeklyReportData
